[package]
name = "rust-blockchain"
version = "0.1.0"
authors = ["lleonesouza <lleonesouza@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
